version: 0.0
os: linux

files:
  - source: /
<<<<<<< Updated upstream
    destination: /home/ubuntu/cicd

=======
    destination: /home/ubuntu
>>>>>>> Stashed changes
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
<<<<<<< Updated upstream
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
=======
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root
>>>>>>> Stashed changes

